(define (problem castle-2-2-8-cards)
(:domain beleaguered-castle)
; Pile 0: spade2 club2
; Pile 1: diamond2 heart2
(:objects
    pile0
    pile1
    clubA
    club2
    heartA
    heart2
    diamondA
    diamond2
    spadeA
    spade2
)
(:init
    (on spade2 pile0)
    (on club2 spade2)
    (on diamond2 pile1)
    (on heart2 diamond2)
    (clear club2)
    (clear heart2)
    (clear clubA)
    (discarded clubA)
    (clear heartA)
    (discarded heartA)
    (clear diamondA)
    (discarded diamondA)
    (clear spadeA)
    (discarded spadeA)
    (has-consecutive-value clubA club2)
    (has-consecutive-value clubA heart2)
    (has-consecutive-value clubA diamond2)
    (has-consecutive-value clubA spade2)
    (has-consecutive-value heartA club2)
    (has-consecutive-value heartA heart2)
    (has-consecutive-value heartA diamond2)
    (has-consecutive-value heartA spade2)
    (has-consecutive-value diamondA club2)
    (has-consecutive-value diamondA heart2)
    (has-consecutive-value diamondA diamond2)
    (has-consecutive-value diamondA spade2)
    (has-consecutive-value spadeA club2)
    (has-consecutive-value spadeA heart2)
    (has-consecutive-value spadeA diamond2)
    (has-consecutive-value spadeA spade2)
    (has-consecutive-value clubA pile0)
    (has-consecutive-value club2 pile0)
    (has-consecutive-value heartA pile0)
    (has-consecutive-value heart2 pile0)
    (has-consecutive-value diamondA pile0)
    (has-consecutive-value diamond2 pile0)
    (has-consecutive-value spadeA pile0)
    (has-consecutive-value spade2 pile0)
    (has-consecutive-value clubA pile1)
    (has-consecutive-value club2 pile1)
    (has-consecutive-value heartA pile1)
    (has-consecutive-value heart2 pile1)
    (has-consecutive-value diamondA pile1)
    (has-consecutive-value diamond2 pile1)
    (has-consecutive-value spadeA pile1)
    (has-consecutive-value spade2 pile1)
    (has-same-suit clubA clubA)
    (has-same-suit clubA club2)
    (has-same-suit club2 clubA)
    (has-same-suit club2 club2)
    (has-same-suit heartA heartA)
    (has-same-suit heartA heart2)
    (has-same-suit heart2 heartA)
    (has-same-suit heart2 heart2)
    (has-same-suit diamondA diamondA)
    (has-same-suit diamondA diamond2)
    (has-same-suit diamond2 diamondA)
    (has-same-suit diamond2 diamond2)
    (has-same-suit spadeA spadeA)
    (has-same-suit spadeA spade2)
    (has-same-suit spade2 spadeA)
    (has-same-suit spade2 spade2)
)
(:goal (and
    (discarded clubA)
    (discarded club2)
    (discarded heartA)
    (discarded heart2)
    (discarded diamondA)
    (discarded diamond2)
    (discarded spadeA)
    (discarded spade2)
)))
