(define (problem castle-5-4-9-cards)
(:domain beleaguered-castle)
; Pile 0: diamond4 heart5 spade4 heart4
; Pile 1: club3 diamond3 club5 spade2
; Pile 2: club2 diamond2 club4 heart2
; Pile 3: diamond5 heart3 spade3 spade5
(:objects
    pile0
    pile1
    pile2
    pile3
    clubA
    club2
    club3
    club4
    club5
    heartA
    heart2
    heart3
    heart4
    heart5
    diamondA
    diamond2
    diamond3
    diamond4
    diamond5
    spadeA
    spade2
    spade3
    spade4
    spade5
)
(:init
    (on diamond4 pile0)
    (on heart5 diamond4)
    (on spade4 heart5)
    (on heart4 spade4)
    (on club3 pile1)
    (on diamond3 club3)
    (on club5 diamond3)
    (on spade2 club5)
    (on club2 pile2)
    (on diamond2 club2)
    (on club4 diamond2)
    (on heart2 club4)
    (on diamond5 pile3)
    (on heart3 diamond5)
    (on spade3 heart3)
    (on spade5 spade3)
    (clear heart4)
    (clear spade2)
    (clear heart2)
    (clear spade5)
    (clear clubA)
    (discarded clubA)
    (clear heartA)
    (discarded heartA)
    (clear diamondA)
    (discarded diamondA)
    (clear spadeA)
    (discarded spadeA)
    (has-consecutive-value clubA club2)
    (has-consecutive-value clubA heart2)
    (has-consecutive-value clubA diamond2)
    (has-consecutive-value clubA spade2)
    (has-consecutive-value club2 club3)
    (has-consecutive-value club2 heart3)
    (has-consecutive-value club2 diamond3)
    (has-consecutive-value club2 spade3)
    (has-consecutive-value club3 club4)
    (has-consecutive-value club3 heart4)
    (has-consecutive-value club3 diamond4)
    (has-consecutive-value club3 spade4)
    (has-consecutive-value club4 club5)
    (has-consecutive-value club4 heart5)
    (has-consecutive-value club4 diamond5)
    (has-consecutive-value club4 spade5)
    (has-consecutive-value heartA club2)
    (has-consecutive-value heartA heart2)
    (has-consecutive-value heartA diamond2)
    (has-consecutive-value heartA spade2)
    (has-consecutive-value heart2 club3)
    (has-consecutive-value heart2 heart3)
    (has-consecutive-value heart2 diamond3)
    (has-consecutive-value heart2 spade3)
    (has-consecutive-value heart3 club4)
    (has-consecutive-value heart3 heart4)
    (has-consecutive-value heart3 diamond4)
    (has-consecutive-value heart3 spade4)
    (has-consecutive-value heart4 club5)
    (has-consecutive-value heart4 heart5)
    (has-consecutive-value heart4 diamond5)
    (has-consecutive-value heart4 spade5)
    (has-consecutive-value diamondA club2)
    (has-consecutive-value diamondA heart2)
    (has-consecutive-value diamondA diamond2)
    (has-consecutive-value diamondA spade2)
    (has-consecutive-value diamond2 club3)
    (has-consecutive-value diamond2 heart3)
    (has-consecutive-value diamond2 diamond3)
    (has-consecutive-value diamond2 spade3)
    (has-consecutive-value diamond3 club4)
    (has-consecutive-value diamond3 heart4)
    (has-consecutive-value diamond3 diamond4)
    (has-consecutive-value diamond3 spade4)
    (has-consecutive-value diamond4 club5)
    (has-consecutive-value diamond4 heart5)
    (has-consecutive-value diamond4 diamond5)
    (has-consecutive-value diamond4 spade5)
    (has-consecutive-value spadeA club2)
    (has-consecutive-value spadeA heart2)
    (has-consecutive-value spadeA diamond2)
    (has-consecutive-value spadeA spade2)
    (has-consecutive-value spade2 club3)
    (has-consecutive-value spade2 heart3)
    (has-consecutive-value spade2 diamond3)
    (has-consecutive-value spade2 spade3)
    (has-consecutive-value spade3 club4)
    (has-consecutive-value spade3 heart4)
    (has-consecutive-value spade3 diamond4)
    (has-consecutive-value spade3 spade4)
    (has-consecutive-value spade4 club5)
    (has-consecutive-value spade4 heart5)
    (has-consecutive-value spade4 diamond5)
    (has-consecutive-value spade4 spade5)
    (has-consecutive-value clubA pile0)
    (has-consecutive-value club2 pile0)
    (has-consecutive-value club3 pile0)
    (has-consecutive-value club4 pile0)
    (has-consecutive-value club5 pile0)
    (has-consecutive-value heartA pile0)
    (has-consecutive-value heart2 pile0)
    (has-consecutive-value heart3 pile0)
    (has-consecutive-value heart4 pile0)
    (has-consecutive-value heart5 pile0)
    (has-consecutive-value diamondA pile0)
    (has-consecutive-value diamond2 pile0)
    (has-consecutive-value diamond3 pile0)
    (has-consecutive-value diamond4 pile0)
    (has-consecutive-value diamond5 pile0)
    (has-consecutive-value spadeA pile0)
    (has-consecutive-value spade2 pile0)
    (has-consecutive-value spade3 pile0)
    (has-consecutive-value spade4 pile0)
    (has-consecutive-value spade5 pile0)
    (has-consecutive-value clubA pile1)
    (has-consecutive-value club2 pile1)
    (has-consecutive-value club3 pile1)
    (has-consecutive-value club4 pile1)
    (has-consecutive-value club5 pile1)
    (has-consecutive-value heartA pile1)
    (has-consecutive-value heart2 pile1)
    (has-consecutive-value heart3 pile1)
    (has-consecutive-value heart4 pile1)
    (has-consecutive-value heart5 pile1)
    (has-consecutive-value diamondA pile1)
    (has-consecutive-value diamond2 pile1)
    (has-consecutive-value diamond3 pile1)
    (has-consecutive-value diamond4 pile1)
    (has-consecutive-value diamond5 pile1)
    (has-consecutive-value spadeA pile1)
    (has-consecutive-value spade2 pile1)
    (has-consecutive-value spade3 pile1)
    (has-consecutive-value spade4 pile1)
    (has-consecutive-value spade5 pile1)
    (has-consecutive-value clubA pile2)
    (has-consecutive-value club2 pile2)
    (has-consecutive-value club3 pile2)
    (has-consecutive-value club4 pile2)
    (has-consecutive-value club5 pile2)
    (has-consecutive-value heartA pile2)
    (has-consecutive-value heart2 pile2)
    (has-consecutive-value heart3 pile2)
    (has-consecutive-value heart4 pile2)
    (has-consecutive-value heart5 pile2)
    (has-consecutive-value diamondA pile2)
    (has-consecutive-value diamond2 pile2)
    (has-consecutive-value diamond3 pile2)
    (has-consecutive-value diamond4 pile2)
    (has-consecutive-value diamond5 pile2)
    (has-consecutive-value spadeA pile2)
    (has-consecutive-value spade2 pile2)
    (has-consecutive-value spade3 pile2)
    (has-consecutive-value spade4 pile2)
    (has-consecutive-value spade5 pile2)
    (has-consecutive-value clubA pile3)
    (has-consecutive-value club2 pile3)
    (has-consecutive-value club3 pile3)
    (has-consecutive-value club4 pile3)
    (has-consecutive-value club5 pile3)
    (has-consecutive-value heartA pile3)
    (has-consecutive-value heart2 pile3)
    (has-consecutive-value heart3 pile3)
    (has-consecutive-value heart4 pile3)
    (has-consecutive-value heart5 pile3)
    (has-consecutive-value diamondA pile3)
    (has-consecutive-value diamond2 pile3)
    (has-consecutive-value diamond3 pile3)
    (has-consecutive-value diamond4 pile3)
    (has-consecutive-value diamond5 pile3)
    (has-consecutive-value spadeA pile3)
    (has-consecutive-value spade2 pile3)
    (has-consecutive-value spade3 pile3)
    (has-consecutive-value spade4 pile3)
    (has-consecutive-value spade5 pile3)
    (has-same-suit clubA clubA)
    (has-same-suit clubA club2)
    (has-same-suit clubA club3)
    (has-same-suit clubA club4)
    (has-same-suit clubA club5)
    (has-same-suit club2 clubA)
    (has-same-suit club2 club2)
    (has-same-suit club2 club3)
    (has-same-suit club2 club4)
    (has-same-suit club2 club5)
    (has-same-suit club3 clubA)
    (has-same-suit club3 club2)
    (has-same-suit club3 club3)
    (has-same-suit club3 club4)
    (has-same-suit club3 club5)
    (has-same-suit club4 clubA)
    (has-same-suit club4 club2)
    (has-same-suit club4 club3)
    (has-same-suit club4 club4)
    (has-same-suit club4 club5)
    (has-same-suit club5 clubA)
    (has-same-suit club5 club2)
    (has-same-suit club5 club3)
    (has-same-suit club5 club4)
    (has-same-suit club5 club5)
    (has-same-suit heartA heartA)
    (has-same-suit heartA heart2)
    (has-same-suit heartA heart3)
    (has-same-suit heartA heart4)
    (has-same-suit heartA heart5)
    (has-same-suit heart2 heartA)
    (has-same-suit heart2 heart2)
    (has-same-suit heart2 heart3)
    (has-same-suit heart2 heart4)
    (has-same-suit heart2 heart5)
    (has-same-suit heart3 heartA)
    (has-same-suit heart3 heart2)
    (has-same-suit heart3 heart3)
    (has-same-suit heart3 heart4)
    (has-same-suit heart3 heart5)
    (has-same-suit heart4 heartA)
    (has-same-suit heart4 heart2)
    (has-same-suit heart4 heart3)
    (has-same-suit heart4 heart4)
    (has-same-suit heart4 heart5)
    (has-same-suit heart5 heartA)
    (has-same-suit heart5 heart2)
    (has-same-suit heart5 heart3)
    (has-same-suit heart5 heart4)
    (has-same-suit heart5 heart5)
    (has-same-suit diamondA diamondA)
    (has-same-suit diamondA diamond2)
    (has-same-suit diamondA diamond3)
    (has-same-suit diamondA diamond4)
    (has-same-suit diamondA diamond5)
    (has-same-suit diamond2 diamondA)
    (has-same-suit diamond2 diamond2)
    (has-same-suit diamond2 diamond3)
    (has-same-suit diamond2 diamond4)
    (has-same-suit diamond2 diamond5)
    (has-same-suit diamond3 diamondA)
    (has-same-suit diamond3 diamond2)
    (has-same-suit diamond3 diamond3)
    (has-same-suit diamond3 diamond4)
    (has-same-suit diamond3 diamond5)
    (has-same-suit diamond4 diamondA)
    (has-same-suit diamond4 diamond2)
    (has-same-suit diamond4 diamond3)
    (has-same-suit diamond4 diamond4)
    (has-same-suit diamond4 diamond5)
    (has-same-suit diamond5 diamondA)
    (has-same-suit diamond5 diamond2)
    (has-same-suit diamond5 diamond3)
    (has-same-suit diamond5 diamond4)
    (has-same-suit diamond5 diamond5)
    (has-same-suit spadeA spadeA)
    (has-same-suit spadeA spade2)
    (has-same-suit spadeA spade3)
    (has-same-suit spadeA spade4)
    (has-same-suit spadeA spade5)
    (has-same-suit spade2 spadeA)
    (has-same-suit spade2 spade2)
    (has-same-suit spade2 spade3)
    (has-same-suit spade2 spade4)
    (has-same-suit spade2 spade5)
    (has-same-suit spade3 spadeA)
    (has-same-suit spade3 spade2)
    (has-same-suit spade3 spade3)
    (has-same-suit spade3 spade4)
    (has-same-suit spade3 spade5)
    (has-same-suit spade4 spadeA)
    (has-same-suit spade4 spade2)
    (has-same-suit spade4 spade3)
    (has-same-suit spade4 spade4)
    (has-same-suit spade4 spade5)
    (has-same-suit spade5 spadeA)
    (has-same-suit spade5 spade2)
    (has-same-suit spade5 spade3)
    (has-same-suit spade5 spade4)
    (has-same-suit spade5 spade5)
)
(:goal (and
    (discarded clubA)
    (discarded club2)
    (discarded club3)
    (discarded club4)
    (discarded club5)
    (discarded heartA)
    (discarded heart2)
    (discarded heart3)
    (discarded heart4)
    (discarded heart5)
    (discarded diamondA)
    (discarded diamond2)
    (discarded diamond3)
    (discarded diamond4)
    (discarded diamond5)
    (discarded spadeA)
    (discarded spade2)
    (discarded spade3)
    (discarded spade4)
    (discarded spade5)
)))
