(define (problem castle-10-6-7-cards)
(:domain beleaguered-castle)
; Pile 0: spade9 club9 club3 diamond5 heart10 spade2
; Pile 1: diamond4 club6 heart9 spade6 diamond10 diamond9
; Pile 2: heart5 club8 heart2 spade8 heart8 diamond7
; Pile 3: diamond2 spade5 heart6 diamond8 diamond3 spade3
; Pile 4: club7 club2 club5 club4 spade7 heart3
; Pile 5: club10 spade10 heart4 diamond6 heart7 spade4
(:objects
    pile0
    pile1
    pile2
    pile3
    pile4
    pile5
    clubA
    club2
    club3
    club4
    club5
    club6
    club7
    club8
    club9
    club10
    heartA
    heart2
    heart3
    heart4
    heart5
    heart6
    heart7
    heart8
    heart9
    heart10
    diamondA
    diamond2
    diamond3
    diamond4
    diamond5
    diamond6
    diamond7
    diamond8
    diamond9
    diamond10
    spadeA
    spade2
    spade3
    spade4
    spade5
    spade6
    spade7
    spade8
    spade9
    spade10
)
(:init
    (on spade9 pile0)
    (on club9 spade9)
    (on club3 club9)
    (on diamond5 club3)
    (on heart10 diamond5)
    (on spade2 heart10)
    (on diamond4 pile1)
    (on club6 diamond4)
    (on heart9 club6)
    (on spade6 heart9)
    (on diamond10 spade6)
    (on diamond9 diamond10)
    (on heart5 pile2)
    (on club8 heart5)
    (on heart2 club8)
    (on spade8 heart2)
    (on heart8 spade8)
    (on diamond7 heart8)
    (on diamond2 pile3)
    (on spade5 diamond2)
    (on heart6 spade5)
    (on diamond8 heart6)
    (on diamond3 diamond8)
    (on spade3 diamond3)
    (on club7 pile4)
    (on club2 club7)
    (on club5 club2)
    (on club4 club5)
    (on spade7 club4)
    (on heart3 spade7)
    (on club10 pile5)
    (on spade10 club10)
    (on heart4 spade10)
    (on diamond6 heart4)
    (on heart7 diamond6)
    (on spade4 heart7)
    (clear spade2)
    (clear diamond9)
    (clear diamond7)
    (clear spade3)
    (clear heart3)
    (clear spade4)
    (clear clubA)
    (discarded clubA)
    (clear heartA)
    (discarded heartA)
    (clear diamondA)
    (discarded diamondA)
    (clear spadeA)
    (discarded spadeA)
    (has-consecutive-value clubA club2)
    (has-consecutive-value clubA heart2)
    (has-consecutive-value clubA diamond2)
    (has-consecutive-value clubA spade2)
    (has-consecutive-value club2 club3)
    (has-consecutive-value club2 heart3)
    (has-consecutive-value club2 diamond3)
    (has-consecutive-value club2 spade3)
    (has-consecutive-value club3 club4)
    (has-consecutive-value club3 heart4)
    (has-consecutive-value club3 diamond4)
    (has-consecutive-value club3 spade4)
    (has-consecutive-value club4 club5)
    (has-consecutive-value club4 heart5)
    (has-consecutive-value club4 diamond5)
    (has-consecutive-value club4 spade5)
    (has-consecutive-value club5 club6)
    (has-consecutive-value club5 heart6)
    (has-consecutive-value club5 diamond6)
    (has-consecutive-value club5 spade6)
    (has-consecutive-value club6 club7)
    (has-consecutive-value club6 heart7)
    (has-consecutive-value club6 diamond7)
    (has-consecutive-value club6 spade7)
    (has-consecutive-value club7 club8)
    (has-consecutive-value club7 heart8)
    (has-consecutive-value club7 diamond8)
    (has-consecutive-value club7 spade8)
    (has-consecutive-value club8 club9)
    (has-consecutive-value club8 heart9)
    (has-consecutive-value club8 diamond9)
    (has-consecutive-value club8 spade9)
    (has-consecutive-value club9 club10)
    (has-consecutive-value club9 heart10)
    (has-consecutive-value club9 diamond10)
    (has-consecutive-value club9 spade10)
    (has-consecutive-value heartA club2)
    (has-consecutive-value heartA heart2)
    (has-consecutive-value heartA diamond2)
    (has-consecutive-value heartA spade2)
    (has-consecutive-value heart2 club3)
    (has-consecutive-value heart2 heart3)
    (has-consecutive-value heart2 diamond3)
    (has-consecutive-value heart2 spade3)
    (has-consecutive-value heart3 club4)
    (has-consecutive-value heart3 heart4)
    (has-consecutive-value heart3 diamond4)
    (has-consecutive-value heart3 spade4)
    (has-consecutive-value heart4 club5)
    (has-consecutive-value heart4 heart5)
    (has-consecutive-value heart4 diamond5)
    (has-consecutive-value heart4 spade5)
    (has-consecutive-value heart5 club6)
    (has-consecutive-value heart5 heart6)
    (has-consecutive-value heart5 diamond6)
    (has-consecutive-value heart5 spade6)
    (has-consecutive-value heart6 club7)
    (has-consecutive-value heart6 heart7)
    (has-consecutive-value heart6 diamond7)
    (has-consecutive-value heart6 spade7)
    (has-consecutive-value heart7 club8)
    (has-consecutive-value heart7 heart8)
    (has-consecutive-value heart7 diamond8)
    (has-consecutive-value heart7 spade8)
    (has-consecutive-value heart8 club9)
    (has-consecutive-value heart8 heart9)
    (has-consecutive-value heart8 diamond9)
    (has-consecutive-value heart8 spade9)
    (has-consecutive-value heart9 club10)
    (has-consecutive-value heart9 heart10)
    (has-consecutive-value heart9 diamond10)
    (has-consecutive-value heart9 spade10)
    (has-consecutive-value diamondA club2)
    (has-consecutive-value diamondA heart2)
    (has-consecutive-value diamondA diamond2)
    (has-consecutive-value diamondA spade2)
    (has-consecutive-value diamond2 club3)
    (has-consecutive-value diamond2 heart3)
    (has-consecutive-value diamond2 diamond3)
    (has-consecutive-value diamond2 spade3)
    (has-consecutive-value diamond3 club4)
    (has-consecutive-value diamond3 heart4)
    (has-consecutive-value diamond3 diamond4)
    (has-consecutive-value diamond3 spade4)
    (has-consecutive-value diamond4 club5)
    (has-consecutive-value diamond4 heart5)
    (has-consecutive-value diamond4 diamond5)
    (has-consecutive-value diamond4 spade5)
    (has-consecutive-value diamond5 club6)
    (has-consecutive-value diamond5 heart6)
    (has-consecutive-value diamond5 diamond6)
    (has-consecutive-value diamond5 spade6)
    (has-consecutive-value diamond6 club7)
    (has-consecutive-value diamond6 heart7)
    (has-consecutive-value diamond6 diamond7)
    (has-consecutive-value diamond6 spade7)
    (has-consecutive-value diamond7 club8)
    (has-consecutive-value diamond7 heart8)
    (has-consecutive-value diamond7 diamond8)
    (has-consecutive-value diamond7 spade8)
    (has-consecutive-value diamond8 club9)
    (has-consecutive-value diamond8 heart9)
    (has-consecutive-value diamond8 diamond9)
    (has-consecutive-value diamond8 spade9)
    (has-consecutive-value diamond9 club10)
    (has-consecutive-value diamond9 heart10)
    (has-consecutive-value diamond9 diamond10)
    (has-consecutive-value diamond9 spade10)
    (has-consecutive-value spadeA club2)
    (has-consecutive-value spadeA heart2)
    (has-consecutive-value spadeA diamond2)
    (has-consecutive-value spadeA spade2)
    (has-consecutive-value spade2 club3)
    (has-consecutive-value spade2 heart3)
    (has-consecutive-value spade2 diamond3)
    (has-consecutive-value spade2 spade3)
    (has-consecutive-value spade3 club4)
    (has-consecutive-value spade3 heart4)
    (has-consecutive-value spade3 diamond4)
    (has-consecutive-value spade3 spade4)
    (has-consecutive-value spade4 club5)
    (has-consecutive-value spade4 heart5)
    (has-consecutive-value spade4 diamond5)
    (has-consecutive-value spade4 spade5)
    (has-consecutive-value spade5 club6)
    (has-consecutive-value spade5 heart6)
    (has-consecutive-value spade5 diamond6)
    (has-consecutive-value spade5 spade6)
    (has-consecutive-value spade6 club7)
    (has-consecutive-value spade6 heart7)
    (has-consecutive-value spade6 diamond7)
    (has-consecutive-value spade6 spade7)
    (has-consecutive-value spade7 club8)
    (has-consecutive-value spade7 heart8)
    (has-consecutive-value spade7 diamond8)
    (has-consecutive-value spade7 spade8)
    (has-consecutive-value spade8 club9)
    (has-consecutive-value spade8 heart9)
    (has-consecutive-value spade8 diamond9)
    (has-consecutive-value spade8 spade9)
    (has-consecutive-value spade9 club10)
    (has-consecutive-value spade9 heart10)
    (has-consecutive-value spade9 diamond10)
    (has-consecutive-value spade9 spade10)
    (has-consecutive-value clubA pile0)
    (has-consecutive-value club2 pile0)
    (has-consecutive-value club3 pile0)
    (has-consecutive-value club4 pile0)
    (has-consecutive-value club5 pile0)
    (has-consecutive-value club6 pile0)
    (has-consecutive-value club7 pile0)
    (has-consecutive-value club8 pile0)
    (has-consecutive-value club9 pile0)
    (has-consecutive-value club10 pile0)
    (has-consecutive-value heartA pile0)
    (has-consecutive-value heart2 pile0)
    (has-consecutive-value heart3 pile0)
    (has-consecutive-value heart4 pile0)
    (has-consecutive-value heart5 pile0)
    (has-consecutive-value heart6 pile0)
    (has-consecutive-value heart7 pile0)
    (has-consecutive-value heart8 pile0)
    (has-consecutive-value heart9 pile0)
    (has-consecutive-value heart10 pile0)
    (has-consecutive-value diamondA pile0)
    (has-consecutive-value diamond2 pile0)
    (has-consecutive-value diamond3 pile0)
    (has-consecutive-value diamond4 pile0)
    (has-consecutive-value diamond5 pile0)
    (has-consecutive-value diamond6 pile0)
    (has-consecutive-value diamond7 pile0)
    (has-consecutive-value diamond8 pile0)
    (has-consecutive-value diamond9 pile0)
    (has-consecutive-value diamond10 pile0)
    (has-consecutive-value spadeA pile0)
    (has-consecutive-value spade2 pile0)
    (has-consecutive-value spade3 pile0)
    (has-consecutive-value spade4 pile0)
    (has-consecutive-value spade5 pile0)
    (has-consecutive-value spade6 pile0)
    (has-consecutive-value spade7 pile0)
    (has-consecutive-value spade8 pile0)
    (has-consecutive-value spade9 pile0)
    (has-consecutive-value spade10 pile0)
    (has-consecutive-value clubA pile1)
    (has-consecutive-value club2 pile1)
    (has-consecutive-value club3 pile1)
    (has-consecutive-value club4 pile1)
    (has-consecutive-value club5 pile1)
    (has-consecutive-value club6 pile1)
    (has-consecutive-value club7 pile1)
    (has-consecutive-value club8 pile1)
    (has-consecutive-value club9 pile1)
    (has-consecutive-value club10 pile1)
    (has-consecutive-value heartA pile1)
    (has-consecutive-value heart2 pile1)
    (has-consecutive-value heart3 pile1)
    (has-consecutive-value heart4 pile1)
    (has-consecutive-value heart5 pile1)
    (has-consecutive-value heart6 pile1)
    (has-consecutive-value heart7 pile1)
    (has-consecutive-value heart8 pile1)
    (has-consecutive-value heart9 pile1)
    (has-consecutive-value heart10 pile1)
    (has-consecutive-value diamondA pile1)
    (has-consecutive-value diamond2 pile1)
    (has-consecutive-value diamond3 pile1)
    (has-consecutive-value diamond4 pile1)
    (has-consecutive-value diamond5 pile1)
    (has-consecutive-value diamond6 pile1)
    (has-consecutive-value diamond7 pile1)
    (has-consecutive-value diamond8 pile1)
    (has-consecutive-value diamond9 pile1)
    (has-consecutive-value diamond10 pile1)
    (has-consecutive-value spadeA pile1)
    (has-consecutive-value spade2 pile1)
    (has-consecutive-value spade3 pile1)
    (has-consecutive-value spade4 pile1)
    (has-consecutive-value spade5 pile1)
    (has-consecutive-value spade6 pile1)
    (has-consecutive-value spade7 pile1)
    (has-consecutive-value spade8 pile1)
    (has-consecutive-value spade9 pile1)
    (has-consecutive-value spade10 pile1)
    (has-consecutive-value clubA pile2)
    (has-consecutive-value club2 pile2)
    (has-consecutive-value club3 pile2)
    (has-consecutive-value club4 pile2)
    (has-consecutive-value club5 pile2)
    (has-consecutive-value club6 pile2)
    (has-consecutive-value club7 pile2)
    (has-consecutive-value club8 pile2)
    (has-consecutive-value club9 pile2)
    (has-consecutive-value club10 pile2)
    (has-consecutive-value heartA pile2)
    (has-consecutive-value heart2 pile2)
    (has-consecutive-value heart3 pile2)
    (has-consecutive-value heart4 pile2)
    (has-consecutive-value heart5 pile2)
    (has-consecutive-value heart6 pile2)
    (has-consecutive-value heart7 pile2)
    (has-consecutive-value heart8 pile2)
    (has-consecutive-value heart9 pile2)
    (has-consecutive-value heart10 pile2)
    (has-consecutive-value diamondA pile2)
    (has-consecutive-value diamond2 pile2)
    (has-consecutive-value diamond3 pile2)
    (has-consecutive-value diamond4 pile2)
    (has-consecutive-value diamond5 pile2)
    (has-consecutive-value diamond6 pile2)
    (has-consecutive-value diamond7 pile2)
    (has-consecutive-value diamond8 pile2)
    (has-consecutive-value diamond9 pile2)
    (has-consecutive-value diamond10 pile2)
    (has-consecutive-value spadeA pile2)
    (has-consecutive-value spade2 pile2)
    (has-consecutive-value spade3 pile2)
    (has-consecutive-value spade4 pile2)
    (has-consecutive-value spade5 pile2)
    (has-consecutive-value spade6 pile2)
    (has-consecutive-value spade7 pile2)
    (has-consecutive-value spade8 pile2)
    (has-consecutive-value spade9 pile2)
    (has-consecutive-value spade10 pile2)
    (has-consecutive-value clubA pile3)
    (has-consecutive-value club2 pile3)
    (has-consecutive-value club3 pile3)
    (has-consecutive-value club4 pile3)
    (has-consecutive-value club5 pile3)
    (has-consecutive-value club6 pile3)
    (has-consecutive-value club7 pile3)
    (has-consecutive-value club8 pile3)
    (has-consecutive-value club9 pile3)
    (has-consecutive-value club10 pile3)
    (has-consecutive-value heartA pile3)
    (has-consecutive-value heart2 pile3)
    (has-consecutive-value heart3 pile3)
    (has-consecutive-value heart4 pile3)
    (has-consecutive-value heart5 pile3)
    (has-consecutive-value heart6 pile3)
    (has-consecutive-value heart7 pile3)
    (has-consecutive-value heart8 pile3)
    (has-consecutive-value heart9 pile3)
    (has-consecutive-value heart10 pile3)
    (has-consecutive-value diamondA pile3)
    (has-consecutive-value diamond2 pile3)
    (has-consecutive-value diamond3 pile3)
    (has-consecutive-value diamond4 pile3)
    (has-consecutive-value diamond5 pile3)
    (has-consecutive-value diamond6 pile3)
    (has-consecutive-value diamond7 pile3)
    (has-consecutive-value diamond8 pile3)
    (has-consecutive-value diamond9 pile3)
    (has-consecutive-value diamond10 pile3)
    (has-consecutive-value spadeA pile3)
    (has-consecutive-value spade2 pile3)
    (has-consecutive-value spade3 pile3)
    (has-consecutive-value spade4 pile3)
    (has-consecutive-value spade5 pile3)
    (has-consecutive-value spade6 pile3)
    (has-consecutive-value spade7 pile3)
    (has-consecutive-value spade8 pile3)
    (has-consecutive-value spade9 pile3)
    (has-consecutive-value spade10 pile3)
    (has-consecutive-value clubA pile4)
    (has-consecutive-value club2 pile4)
    (has-consecutive-value club3 pile4)
    (has-consecutive-value club4 pile4)
    (has-consecutive-value club5 pile4)
    (has-consecutive-value club6 pile4)
    (has-consecutive-value club7 pile4)
    (has-consecutive-value club8 pile4)
    (has-consecutive-value club9 pile4)
    (has-consecutive-value club10 pile4)
    (has-consecutive-value heartA pile4)
    (has-consecutive-value heart2 pile4)
    (has-consecutive-value heart3 pile4)
    (has-consecutive-value heart4 pile4)
    (has-consecutive-value heart5 pile4)
    (has-consecutive-value heart6 pile4)
    (has-consecutive-value heart7 pile4)
    (has-consecutive-value heart8 pile4)
    (has-consecutive-value heart9 pile4)
    (has-consecutive-value heart10 pile4)
    (has-consecutive-value diamondA pile4)
    (has-consecutive-value diamond2 pile4)
    (has-consecutive-value diamond3 pile4)
    (has-consecutive-value diamond4 pile4)
    (has-consecutive-value diamond5 pile4)
    (has-consecutive-value diamond6 pile4)
    (has-consecutive-value diamond7 pile4)
    (has-consecutive-value diamond8 pile4)
    (has-consecutive-value diamond9 pile4)
    (has-consecutive-value diamond10 pile4)
    (has-consecutive-value spadeA pile4)
    (has-consecutive-value spade2 pile4)
    (has-consecutive-value spade3 pile4)
    (has-consecutive-value spade4 pile4)
    (has-consecutive-value spade5 pile4)
    (has-consecutive-value spade6 pile4)
    (has-consecutive-value spade7 pile4)
    (has-consecutive-value spade8 pile4)
    (has-consecutive-value spade9 pile4)
    (has-consecutive-value spade10 pile4)
    (has-consecutive-value clubA pile5)
    (has-consecutive-value club2 pile5)
    (has-consecutive-value club3 pile5)
    (has-consecutive-value club4 pile5)
    (has-consecutive-value club5 pile5)
    (has-consecutive-value club6 pile5)
    (has-consecutive-value club7 pile5)
    (has-consecutive-value club8 pile5)
    (has-consecutive-value club9 pile5)
    (has-consecutive-value club10 pile5)
    (has-consecutive-value heartA pile5)
    (has-consecutive-value heart2 pile5)
    (has-consecutive-value heart3 pile5)
    (has-consecutive-value heart4 pile5)
    (has-consecutive-value heart5 pile5)
    (has-consecutive-value heart6 pile5)
    (has-consecutive-value heart7 pile5)
    (has-consecutive-value heart8 pile5)
    (has-consecutive-value heart9 pile5)
    (has-consecutive-value heart10 pile5)
    (has-consecutive-value diamondA pile5)
    (has-consecutive-value diamond2 pile5)
    (has-consecutive-value diamond3 pile5)
    (has-consecutive-value diamond4 pile5)
    (has-consecutive-value diamond5 pile5)
    (has-consecutive-value diamond6 pile5)
    (has-consecutive-value diamond7 pile5)
    (has-consecutive-value diamond8 pile5)
    (has-consecutive-value diamond9 pile5)
    (has-consecutive-value diamond10 pile5)
    (has-consecutive-value spadeA pile5)
    (has-consecutive-value spade2 pile5)
    (has-consecutive-value spade3 pile5)
    (has-consecutive-value spade4 pile5)
    (has-consecutive-value spade5 pile5)
    (has-consecutive-value spade6 pile5)
    (has-consecutive-value spade7 pile5)
    (has-consecutive-value spade8 pile5)
    (has-consecutive-value spade9 pile5)
    (has-consecutive-value spade10 pile5)
    (has-same-suit clubA clubA)
    (has-same-suit clubA club2)
    (has-same-suit clubA club3)
    (has-same-suit clubA club4)
    (has-same-suit clubA club5)
    (has-same-suit clubA club6)
    (has-same-suit clubA club7)
    (has-same-suit clubA club8)
    (has-same-suit clubA club9)
    (has-same-suit clubA club10)
    (has-same-suit club2 clubA)
    (has-same-suit club2 club2)
    (has-same-suit club2 club3)
    (has-same-suit club2 club4)
    (has-same-suit club2 club5)
    (has-same-suit club2 club6)
    (has-same-suit club2 club7)
    (has-same-suit club2 club8)
    (has-same-suit club2 club9)
    (has-same-suit club2 club10)
    (has-same-suit club3 clubA)
    (has-same-suit club3 club2)
    (has-same-suit club3 club3)
    (has-same-suit club3 club4)
    (has-same-suit club3 club5)
    (has-same-suit club3 club6)
    (has-same-suit club3 club7)
    (has-same-suit club3 club8)
    (has-same-suit club3 club9)
    (has-same-suit club3 club10)
    (has-same-suit club4 clubA)
    (has-same-suit club4 club2)
    (has-same-suit club4 club3)
    (has-same-suit club4 club4)
    (has-same-suit club4 club5)
    (has-same-suit club4 club6)
    (has-same-suit club4 club7)
    (has-same-suit club4 club8)
    (has-same-suit club4 club9)
    (has-same-suit club4 club10)
    (has-same-suit club5 clubA)
    (has-same-suit club5 club2)
    (has-same-suit club5 club3)
    (has-same-suit club5 club4)
    (has-same-suit club5 club5)
    (has-same-suit club5 club6)
    (has-same-suit club5 club7)
    (has-same-suit club5 club8)
    (has-same-suit club5 club9)
    (has-same-suit club5 club10)
    (has-same-suit club6 clubA)
    (has-same-suit club6 club2)
    (has-same-suit club6 club3)
    (has-same-suit club6 club4)
    (has-same-suit club6 club5)
    (has-same-suit club6 club6)
    (has-same-suit club6 club7)
    (has-same-suit club6 club8)
    (has-same-suit club6 club9)
    (has-same-suit club6 club10)
    (has-same-suit club7 clubA)
    (has-same-suit club7 club2)
    (has-same-suit club7 club3)
    (has-same-suit club7 club4)
    (has-same-suit club7 club5)
    (has-same-suit club7 club6)
    (has-same-suit club7 club7)
    (has-same-suit club7 club8)
    (has-same-suit club7 club9)
    (has-same-suit club7 club10)
    (has-same-suit club8 clubA)
    (has-same-suit club8 club2)
    (has-same-suit club8 club3)
    (has-same-suit club8 club4)
    (has-same-suit club8 club5)
    (has-same-suit club8 club6)
    (has-same-suit club8 club7)
    (has-same-suit club8 club8)
    (has-same-suit club8 club9)
    (has-same-suit club8 club10)
    (has-same-suit club9 clubA)
    (has-same-suit club9 club2)
    (has-same-suit club9 club3)
    (has-same-suit club9 club4)
    (has-same-suit club9 club5)
    (has-same-suit club9 club6)
    (has-same-suit club9 club7)
    (has-same-suit club9 club8)
    (has-same-suit club9 club9)
    (has-same-suit club9 club10)
    (has-same-suit club10 clubA)
    (has-same-suit club10 club2)
    (has-same-suit club10 club3)
    (has-same-suit club10 club4)
    (has-same-suit club10 club5)
    (has-same-suit club10 club6)
    (has-same-suit club10 club7)
    (has-same-suit club10 club8)
    (has-same-suit club10 club9)
    (has-same-suit club10 club10)
    (has-same-suit heartA heartA)
    (has-same-suit heartA heart2)
    (has-same-suit heartA heart3)
    (has-same-suit heartA heart4)
    (has-same-suit heartA heart5)
    (has-same-suit heartA heart6)
    (has-same-suit heartA heart7)
    (has-same-suit heartA heart8)
    (has-same-suit heartA heart9)
    (has-same-suit heartA heart10)
    (has-same-suit heart2 heartA)
    (has-same-suit heart2 heart2)
    (has-same-suit heart2 heart3)
    (has-same-suit heart2 heart4)
    (has-same-suit heart2 heart5)
    (has-same-suit heart2 heart6)
    (has-same-suit heart2 heart7)
    (has-same-suit heart2 heart8)
    (has-same-suit heart2 heart9)
    (has-same-suit heart2 heart10)
    (has-same-suit heart3 heartA)
    (has-same-suit heart3 heart2)
    (has-same-suit heart3 heart3)
    (has-same-suit heart3 heart4)
    (has-same-suit heart3 heart5)
    (has-same-suit heart3 heart6)
    (has-same-suit heart3 heart7)
    (has-same-suit heart3 heart8)
    (has-same-suit heart3 heart9)
    (has-same-suit heart3 heart10)
    (has-same-suit heart4 heartA)
    (has-same-suit heart4 heart2)
    (has-same-suit heart4 heart3)
    (has-same-suit heart4 heart4)
    (has-same-suit heart4 heart5)
    (has-same-suit heart4 heart6)
    (has-same-suit heart4 heart7)
    (has-same-suit heart4 heart8)
    (has-same-suit heart4 heart9)
    (has-same-suit heart4 heart10)
    (has-same-suit heart5 heartA)
    (has-same-suit heart5 heart2)
    (has-same-suit heart5 heart3)
    (has-same-suit heart5 heart4)
    (has-same-suit heart5 heart5)
    (has-same-suit heart5 heart6)
    (has-same-suit heart5 heart7)
    (has-same-suit heart5 heart8)
    (has-same-suit heart5 heart9)
    (has-same-suit heart5 heart10)
    (has-same-suit heart6 heartA)
    (has-same-suit heart6 heart2)
    (has-same-suit heart6 heart3)
    (has-same-suit heart6 heart4)
    (has-same-suit heart6 heart5)
    (has-same-suit heart6 heart6)
    (has-same-suit heart6 heart7)
    (has-same-suit heart6 heart8)
    (has-same-suit heart6 heart9)
    (has-same-suit heart6 heart10)
    (has-same-suit heart7 heartA)
    (has-same-suit heart7 heart2)
    (has-same-suit heart7 heart3)
    (has-same-suit heart7 heart4)
    (has-same-suit heart7 heart5)
    (has-same-suit heart7 heart6)
    (has-same-suit heart7 heart7)
    (has-same-suit heart7 heart8)
    (has-same-suit heart7 heart9)
    (has-same-suit heart7 heart10)
    (has-same-suit heart8 heartA)
    (has-same-suit heart8 heart2)
    (has-same-suit heart8 heart3)
    (has-same-suit heart8 heart4)
    (has-same-suit heart8 heart5)
    (has-same-suit heart8 heart6)
    (has-same-suit heart8 heart7)
    (has-same-suit heart8 heart8)
    (has-same-suit heart8 heart9)
    (has-same-suit heart8 heart10)
    (has-same-suit heart9 heartA)
    (has-same-suit heart9 heart2)
    (has-same-suit heart9 heart3)
    (has-same-suit heart9 heart4)
    (has-same-suit heart9 heart5)
    (has-same-suit heart9 heart6)
    (has-same-suit heart9 heart7)
    (has-same-suit heart9 heart8)
    (has-same-suit heart9 heart9)
    (has-same-suit heart9 heart10)
    (has-same-suit heart10 heartA)
    (has-same-suit heart10 heart2)
    (has-same-suit heart10 heart3)
    (has-same-suit heart10 heart4)
    (has-same-suit heart10 heart5)
    (has-same-suit heart10 heart6)
    (has-same-suit heart10 heart7)
    (has-same-suit heart10 heart8)
    (has-same-suit heart10 heart9)
    (has-same-suit heart10 heart10)
    (has-same-suit diamondA diamondA)
    (has-same-suit diamondA diamond2)
    (has-same-suit diamondA diamond3)
    (has-same-suit diamondA diamond4)
    (has-same-suit diamondA diamond5)
    (has-same-suit diamondA diamond6)
    (has-same-suit diamondA diamond7)
    (has-same-suit diamondA diamond8)
    (has-same-suit diamondA diamond9)
    (has-same-suit diamondA diamond10)
    (has-same-suit diamond2 diamondA)
    (has-same-suit diamond2 diamond2)
    (has-same-suit diamond2 diamond3)
    (has-same-suit diamond2 diamond4)
    (has-same-suit diamond2 diamond5)
    (has-same-suit diamond2 diamond6)
    (has-same-suit diamond2 diamond7)
    (has-same-suit diamond2 diamond8)
    (has-same-suit diamond2 diamond9)
    (has-same-suit diamond2 diamond10)
    (has-same-suit diamond3 diamondA)
    (has-same-suit diamond3 diamond2)
    (has-same-suit diamond3 diamond3)
    (has-same-suit diamond3 diamond4)
    (has-same-suit diamond3 diamond5)
    (has-same-suit diamond3 diamond6)
    (has-same-suit diamond3 diamond7)
    (has-same-suit diamond3 diamond8)
    (has-same-suit diamond3 diamond9)
    (has-same-suit diamond3 diamond10)
    (has-same-suit diamond4 diamondA)
    (has-same-suit diamond4 diamond2)
    (has-same-suit diamond4 diamond3)
    (has-same-suit diamond4 diamond4)
    (has-same-suit diamond4 diamond5)
    (has-same-suit diamond4 diamond6)
    (has-same-suit diamond4 diamond7)
    (has-same-suit diamond4 diamond8)
    (has-same-suit diamond4 diamond9)
    (has-same-suit diamond4 diamond10)
    (has-same-suit diamond5 diamondA)
    (has-same-suit diamond5 diamond2)
    (has-same-suit diamond5 diamond3)
    (has-same-suit diamond5 diamond4)
    (has-same-suit diamond5 diamond5)
    (has-same-suit diamond5 diamond6)
    (has-same-suit diamond5 diamond7)
    (has-same-suit diamond5 diamond8)
    (has-same-suit diamond5 diamond9)
    (has-same-suit diamond5 diamond10)
    (has-same-suit diamond6 diamondA)
    (has-same-suit diamond6 diamond2)
    (has-same-suit diamond6 diamond3)
    (has-same-suit diamond6 diamond4)
    (has-same-suit diamond6 diamond5)
    (has-same-suit diamond6 diamond6)
    (has-same-suit diamond6 diamond7)
    (has-same-suit diamond6 diamond8)
    (has-same-suit diamond6 diamond9)
    (has-same-suit diamond6 diamond10)
    (has-same-suit diamond7 diamondA)
    (has-same-suit diamond7 diamond2)
    (has-same-suit diamond7 diamond3)
    (has-same-suit diamond7 diamond4)
    (has-same-suit diamond7 diamond5)
    (has-same-suit diamond7 diamond6)
    (has-same-suit diamond7 diamond7)
    (has-same-suit diamond7 diamond8)
    (has-same-suit diamond7 diamond9)
    (has-same-suit diamond7 diamond10)
    (has-same-suit diamond8 diamondA)
    (has-same-suit diamond8 diamond2)
    (has-same-suit diamond8 diamond3)
    (has-same-suit diamond8 diamond4)
    (has-same-suit diamond8 diamond5)
    (has-same-suit diamond8 diamond6)
    (has-same-suit diamond8 diamond7)
    (has-same-suit diamond8 diamond8)
    (has-same-suit diamond8 diamond9)
    (has-same-suit diamond8 diamond10)
    (has-same-suit diamond9 diamondA)
    (has-same-suit diamond9 diamond2)
    (has-same-suit diamond9 diamond3)
    (has-same-suit diamond9 diamond4)
    (has-same-suit diamond9 diamond5)
    (has-same-suit diamond9 diamond6)
    (has-same-suit diamond9 diamond7)
    (has-same-suit diamond9 diamond8)
    (has-same-suit diamond9 diamond9)
    (has-same-suit diamond9 diamond10)
    (has-same-suit diamond10 diamondA)
    (has-same-suit diamond10 diamond2)
    (has-same-suit diamond10 diamond3)
    (has-same-suit diamond10 diamond4)
    (has-same-suit diamond10 diamond5)
    (has-same-suit diamond10 diamond6)
    (has-same-suit diamond10 diamond7)
    (has-same-suit diamond10 diamond8)
    (has-same-suit diamond10 diamond9)
    (has-same-suit diamond10 diamond10)
    (has-same-suit spadeA spadeA)
    (has-same-suit spadeA spade2)
    (has-same-suit spadeA spade3)
    (has-same-suit spadeA spade4)
    (has-same-suit spadeA spade5)
    (has-same-suit spadeA spade6)
    (has-same-suit spadeA spade7)
    (has-same-suit spadeA spade8)
    (has-same-suit spadeA spade9)
    (has-same-suit spadeA spade10)
    (has-same-suit spade2 spadeA)
    (has-same-suit spade2 spade2)
    (has-same-suit spade2 spade3)
    (has-same-suit spade2 spade4)
    (has-same-suit spade2 spade5)
    (has-same-suit spade2 spade6)
    (has-same-suit spade2 spade7)
    (has-same-suit spade2 spade8)
    (has-same-suit spade2 spade9)
    (has-same-suit spade2 spade10)
    (has-same-suit spade3 spadeA)
    (has-same-suit spade3 spade2)
    (has-same-suit spade3 spade3)
    (has-same-suit spade3 spade4)
    (has-same-suit spade3 spade5)
    (has-same-suit spade3 spade6)
    (has-same-suit spade3 spade7)
    (has-same-suit spade3 spade8)
    (has-same-suit spade3 spade9)
    (has-same-suit spade3 spade10)
    (has-same-suit spade4 spadeA)
    (has-same-suit spade4 spade2)
    (has-same-suit spade4 spade3)
    (has-same-suit spade4 spade4)
    (has-same-suit spade4 spade5)
    (has-same-suit spade4 spade6)
    (has-same-suit spade4 spade7)
    (has-same-suit spade4 spade8)
    (has-same-suit spade4 spade9)
    (has-same-suit spade4 spade10)
    (has-same-suit spade5 spadeA)
    (has-same-suit spade5 spade2)
    (has-same-suit spade5 spade3)
    (has-same-suit spade5 spade4)
    (has-same-suit spade5 spade5)
    (has-same-suit spade5 spade6)
    (has-same-suit spade5 spade7)
    (has-same-suit spade5 spade8)
    (has-same-suit spade5 spade9)
    (has-same-suit spade5 spade10)
    (has-same-suit spade6 spadeA)
    (has-same-suit spade6 spade2)
    (has-same-suit spade6 spade3)
    (has-same-suit spade6 spade4)
    (has-same-suit spade6 spade5)
    (has-same-suit spade6 spade6)
    (has-same-suit spade6 spade7)
    (has-same-suit spade6 spade8)
    (has-same-suit spade6 spade9)
    (has-same-suit spade6 spade10)
    (has-same-suit spade7 spadeA)
    (has-same-suit spade7 spade2)
    (has-same-suit spade7 spade3)
    (has-same-suit spade7 spade4)
    (has-same-suit spade7 spade5)
    (has-same-suit spade7 spade6)
    (has-same-suit spade7 spade7)
    (has-same-suit spade7 spade8)
    (has-same-suit spade7 spade9)
    (has-same-suit spade7 spade10)
    (has-same-suit spade8 spadeA)
    (has-same-suit spade8 spade2)
    (has-same-suit spade8 spade3)
    (has-same-suit spade8 spade4)
    (has-same-suit spade8 spade5)
    (has-same-suit spade8 spade6)
    (has-same-suit spade8 spade7)
    (has-same-suit spade8 spade8)
    (has-same-suit spade8 spade9)
    (has-same-suit spade8 spade10)
    (has-same-suit spade9 spadeA)
    (has-same-suit spade9 spade2)
    (has-same-suit spade9 spade3)
    (has-same-suit spade9 spade4)
    (has-same-suit spade9 spade5)
    (has-same-suit spade9 spade6)
    (has-same-suit spade9 spade7)
    (has-same-suit spade9 spade8)
    (has-same-suit spade9 spade9)
    (has-same-suit spade9 spade10)
    (has-same-suit spade10 spadeA)
    (has-same-suit spade10 spade2)
    (has-same-suit spade10 spade3)
    (has-same-suit spade10 spade4)
    (has-same-suit spade10 spade5)
    (has-same-suit spade10 spade6)
    (has-same-suit spade10 spade7)
    (has-same-suit spade10 spade8)
    (has-same-suit spade10 spade9)
    (has-same-suit spade10 spade10)
)
(:goal (and
    (discarded clubA)
    (discarded club2)
    (discarded club3)
    (discarded club4)
    (discarded club5)
    (discarded club6)
    (discarded club7)
    (discarded club8)
    (discarded club9)
    (discarded club10)
    (discarded heartA)
    (discarded heart2)
    (discarded heart3)
    (discarded heart4)
    (discarded heart5)
    (discarded heart6)
    (discarded heart7)
    (discarded heart8)
    (discarded heart9)
    (discarded heart10)
    (discarded diamondA)
    (discarded diamond2)
    (discarded diamond3)
    (discarded diamond4)
    (discarded diamond5)
    (discarded diamond6)
    (discarded diamond7)
    (discarded diamond8)
    (discarded diamond9)
    (discarded diamond10)
    (discarded spadeA)
    (discarded spade2)
    (discarded spade3)
    (discarded spade4)
    (discarded spade5)
    (discarded spade6)
    (discarded spade7)
    (discarded spade8)
    (discarded spade9)
    (discarded spade10)
)))
